// DO NOT EDIT THIS FILE //
import { Book } from "@/lib/type"
import { JSONFilePreset } from "lowdb/node"

const randomError = 0.5
const slowConnexion = true
const serverResponseTime = 2000

type BddDataType = {
  books?: Book[]
}

const defaultData = (await JSONFilePreset("./src/db/default.db.json", { books: [] } as BddDataType)).data

export default async function lowDb() {
  return initDb()
}
// initialize db with default data and file creation
async function initDb() {
  const db = await JSONFilePreset("./src/db/db.json", defaultData)
  if (db.data.books?.length === 1) {
    const book = db.data.books[0]
    db.update(({ books }: BddDataType) => books?.push({ ...book, id: 2 }))
  }

  return db
}

//BOOKS
export async function getBooks() {
  console.log("getBooks dao")
  const db = await lowDb()
  const { books } = db.data
  return sortByDate(books, "asc")
}

export async function addBook(book: Book) {
  console.log("addBook", book)
  await simulateUnstableServer({ slow: true })
  const db = await lowDb()
  await db.update(({ books }) => {
    books?.push({
      id: books.length + 1,
      title: book.title,
      chapters: book.chapters,
      questions: book.questions,
      createdAt: book.createdAt ?? new Date().toISOString(),
      updatedAt: book.updatedAt ?? new Date().toISOString(),
    })
  })
}

export async function persistBook(book: Book) {
  console.log(typeof book.id)
  await (book.id ? updateBook(book) : addBook(book))
}

export async function updateBook(book: Book) {
  console.log("updateBook", book)
  await simulateUnstableServer({ slow: true })
  book.updatedAt = book.updatedAt ?? new Date().toISOString()
  const db = await lowDb()
  await db.update(({ books }) => {
    updateById(books ?? [], book)
  })
}

export async function deleteBook(id: number) {
  console.log("deleteBook", id)
  const db = await lowDb()
  await db.update(({ books }) => {
    deleteById(books ?? [], id)
  })
}

export async function getBookById(id: number) {
  console.log("getBookById", id)
  const db = await lowDb()
  const { books } = db.data
  return books?.find((book) => book.id === id)
}

export async function getBookByName(name: string) {
  console.log("getBookByName", name)
  const db = await lowDb()
  const { books } = db.data
  const lowerCaseName = name.toLowerCase()
  return books?.find((book) => book.title.toLowerCase() === lowerCaseName)
}

interface Identifiable {
  id: number | string
}

// Generic function to update an element from an array
function updateById<T extends Identifiable>(items: T[], updatedItem: T): void {
  const index = items.findIndex((item) => item.id === updatedItem.id)
  if (index === -1) {
    throw new Error(`Item with id ${updatedItem.id} not found`)
  }
  items[index] = updatedItem
}

// Generic function to delete an element from an array
function deleteById<T extends Identifiable>(items: T[], itemId: number | string): void {
  const index = items.findIndex((item) => item.id === itemId)
  if (index === -1) {
    throw new Error(`Item with id ${itemId} not found`)
  } else {
    items.splice(index, 1)
  }
}

interface Sortable {
  createdAt?: string
  updatedAt?: string
}

function sortByDate<T extends Sortable>(items?: T[], sortOrder: "asc" | "desc" = "asc"): T[] {
  if (!items) {
    return []
  }
  return items.toSorted((a, b) => {
    const dateA = a.createdAt ? new Date(a.createdAt) : new Date()
    const dateB = b.createdAt ? new Date(b.createdAt) : new Date()
    const result = dateA.getTime() - dateB.getTime()
    return sortOrder === "asc" ? result : -result
  })
}

async function simulateUnstableServer({
  slow = slowConnexion,
  random = randomError,
  serverTime = serverResponseTime,
}: { slow?: boolean; random?: number; serverTime?: number } = {}) {
  if (slow) {
    await new Promise((resolve) => setTimeout(resolve, serverTime))
  }
  if (random && Math.random() > random) {
    throw new Error("Internal server error")
  }
}
